// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIU3TkZ8gEForzHQ1K9sV3IwpDnirT2s',
    appId: '1:261481012404:android:3380cd98a547c293964be1',
    messagingSenderId: '261481012404',
    projectId: 'goodiez-655a0',
    storageBucket: 'goodiez-655a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHAU7DjJWyRxb-GL5awgxauON8DBVRSE',
    appId: '1:261481012404:ios:38b4cf37175bc8fe964be1',
    messagingSenderId: '261481012404',
    projectId: 'goodiez-655a0',
    storageBucket: 'goodiez-655a0.appspot.com',
    androidClientId: '261481012404-0fvfpvtn8vrrqsvosk2fu1q7jn846sfl.apps.googleusercontent.com',
    iosClientId: '261481012404-q5vnvr6cvj7rrdj8d2nav0n3i63fobhr.apps.googleusercontent.com',
    iosBundleId: 'io.goodiez.abalone.goodiezAbalone',
  );
}
